version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfe-scraping
    ports:
      - "8080:8080" 
    volumes:
      - ./data:/app/output_images
      - ./data:/app/output_sheets
      - ./data:/app/output_screenshots
    depends_on:
      - elasticsearch
      - logstash
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
